# Generated by Django 5.2.8 on 2025-11-17 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.ImageField(upload_to='images/')),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(choices=[('Adilabad', 'Adilabad'), ('Bhadradri Kothagudem', 'Bhadradri Kothagudem'), ('Hanamkonda', 'Hanamkonda'), ('Hyderabad', 'Hyderabad'), ('Jagitial', 'Jagitial'), ('Jangaon', 'Jangaon'), ('Jayashankar Bhupalpally', 'Jayashankar Bhupalpally'), ('Jogulamba Gadwal', 'Jogulamba Gadwal'), ('Kamareddy', 'Kamareddy'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Komaram Bheem Asifabad', 'Komaram Bheem Asifabad'), ('Mahabubabad', 'Mahabubabad'), ('Mahabubnagar', 'Mahabubnagar'), ('Mancherial', 'Mancherial'), ('Medak', 'Medak'), ('Medchal–Malkajgiri', 'Medchal–Malkajgiri'), ('Mulugu', 'Mulugu'), ('Nagarkurnool', 'Nagarkurnool'), ('Nalgonda', 'Nalgonda'), ('Narayanpet', 'Narayanpet'), ('Nirmal', 'Nirmal'), ('Nizamabad', 'Nizamabad'), ('Peddapalli', 'Peddapalli'), ('Rajanna Sircilla', 'Rajanna Sircilla'), ('Ranga Reddy', 'Ranga Reddy'), ('Sangareddy', 'Sangareddy'), ('Siddipet', 'Siddipet'), ('Suryapet', 'Suryapet'), ('Vikarabad', 'Vikarabad'), ('Wanaparthy', 'Wanaparthy'), ('Warangal', 'Warangal'), ('Yadadri Bhuvanagiri', 'Yadadri Bhuvanagiri')], max_length=33)),
                ('hospital_name', models.CharField(default='Unknown Hospital', max_length=200)),
                ('blood_req', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('place', models.CharField(choices=[('Adilabad', 'Adilabad'), ('Bhadradri Kothagudem', 'Bhadradri Kothagudem'), ('Hanamkonda', 'Hanamkonda'), ('Hyderabad', 'Hyderabad'), ('Jagitial', 'Jagitial'), ('Jangaon', 'Jangaon'), ('Jayashankar Bhupalpally', 'Jayashankar Bhupalpally'), ('Jogulamba Gadwal', 'Jogulamba Gadwal'), ('Kamareddy', 'Kamareddy'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Komaram Bheem Asifabad', 'Komaram Bheem Asifabad'), ('Mahabubabad', 'Mahabubabad'), ('Mahabubnagar', 'Mahabubnagar'), ('Mancherial', 'Mancherial'), ('Medak', 'Medak'), ('Medchal–Malkajgiri', 'Medchal–Malkajgiri'), ('Mulugu', 'Mulugu'), ('Nagarkurnool', 'Nagarkurnool'), ('Nalgonda', 'Nalgonda'), ('Narayanpet', 'Narayanpet'), ('Nirmal', 'Nirmal'), ('Nizamabad', 'Nizamabad'), ('Peddapalli', 'Peddapalli'), ('Rajanna Sircilla', 'Rajanna Sircilla'), ('Ranga Reddy', 'Ranga Reddy'), ('Sangareddy', 'Sangareddy'), ('Siddipet', 'Siddipet'), ('Suryapet', 'Suryapet'), ('Vikarabad', 'Vikarabad'), ('Wanaparthy', 'Wanaparthy'), ('Warangal', 'Warangal'), ('Yadadri Bhuvanagiri', 'Yadadri Bhuvanagiri')], max_length=33)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
